Harris-corner-concept

In [52]:
import numpy as np
import cv2 as cv

In [53]:
img = cv.imread(r"C:\Users\suruj\PYTHON-IMAGE-PROCESSING\demo\pht\shape.png")
img = cv.resize(img,(1200,700))
cv.imshow('img',img)

In [54]:
#gray conversion 
gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
gray = np.float32(gray) # demand of harris concept that the float should be of 32 size
print(gray)

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [22. 22. 22. ... 62. 62. 63.]
 [21. 21. 21. ... 62. 62. 62.]
 [22. 22. 22. ... 62. 62. 63.]]


In [55]:
#detect corner
res = cv.cornerHarris(gray, 2 , 3 , 0.04) # changing parameter (gray , _ , 3, 0.004)
#print(res)

res = cv.dilate(res, None)
img[res > 0.01 * res.max()] = [0, 0 , 255] #marked color

In [56]:
cv.imshow('dst', img)
cv.waitKey(0)
cv.destroyAllWindows()